from enum import StrEnum


class SourceType(StrEnum):
    UPLOADED_PDF = "UPLOADED_PDF"
    LIVE_FULL_TEXT = "LIVE_FULL_TEXT"
    LIVE_ABSTRACT = "LIVE_ABSTRACT"


class Stance(StrEnum):
    SUPPORTING = "SUPPORTING"
    CONTRADICTING = "CONTRADICTING"
    QUALIFYING = "QUALIFYING"
    IRRELEVANT = "IRRELEVANT"


class AnalysisStatus(StrEnum):
    QUEUED = "QUEUED"
    PROCESSING_UPLOADS = "PROCESSING_UPLOADS"
    SEARCHING = "SEARCHING"
    FETCHING_FULL_TEXT = "FETCHING_FULL_TEXT"
    INDEXING = "INDEXING"
    RETRIEVING = "RETRIEVING"
    ANALYZING_EVIDENCE = "ANALYZING_EVIDENCE"
    SYNTHESIZING = "SYNTHESIZING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
